export type Permission =
  | 'tenant:manage'
  | 'billing:manage'
  | 'locations:crud'
  | 'users:crud'
  | 'staff:crud'
  | 'clients:crud'
  | 'reports:view_all'
  | 'location:manage'
  | 'programs:crud'
  | 'reports:view_location'
  | 'clients:read'
  | 'plans:crud'
  | 'attendance:crud'
  | 'schedule:read/write_limited'
  | 'self:read/write'
  | 'plans:read'
  | 'attendance:read';
