export const PHASE1_FEATURE_FLAG_KEYS = {
  email2sv: 'FEATURE_EMAIL_2SV',
  secureProfileUpdates: 'FEATURE_SECURE_PROFILE_UPDATES',
  tenantSlugEditor: 'FEATURE_TENANT_SLUG_EDITOR',
  publicSiteAutoprovision: 'FEATURE_PUBLIC_SITE_AUTOPROVISION',
  roleOnboardingV2: 'FEATURE_ROLE_ONBOARDING_V2',
} as const;

export type Phase1FeatureFlagKey = (typeof PHASE1_FEATURE_FLAG_KEYS)[keyof typeof PHASE1_FEATURE_FLAG_KEYS];

export const PHASE1_FEATURE_FLAG_DEFAULTS: Record<Phase1FeatureFlagKey, boolean> = {
  FEATURE_EMAIL_2SV: false,
  FEATURE_SECURE_PROFILE_UPDATES: false,
  FEATURE_TENANT_SLUG_EDITOR: false,
  FEATURE_PUBLIC_SITE_AUTOPROVISION: false,
  FEATURE_ROLE_ONBOARDING_V2: false,
};

export function getPhase1FeatureFlags(flags: Record<string, boolean> | null | undefined): Record<Phase1FeatureFlagKey, boolean> {
  return {
    FEATURE_EMAIL_2SV: Boolean(flags?.FEATURE_EMAIL_2SV ?? PHASE1_FEATURE_FLAG_DEFAULTS.FEATURE_EMAIL_2SV),
    FEATURE_SECURE_PROFILE_UPDATES: Boolean(
      flags?.FEATURE_SECURE_PROFILE_UPDATES ?? PHASE1_FEATURE_FLAG_DEFAULTS.FEATURE_SECURE_PROFILE_UPDATES,
    ),
    FEATURE_TENANT_SLUG_EDITOR: Boolean(
      flags?.FEATURE_TENANT_SLUG_EDITOR ?? PHASE1_FEATURE_FLAG_DEFAULTS.FEATURE_TENANT_SLUG_EDITOR,
    ),
    FEATURE_PUBLIC_SITE_AUTOPROVISION: Boolean(
      flags?.FEATURE_PUBLIC_SITE_AUTOPROVISION ?? PHASE1_FEATURE_FLAG_DEFAULTS.FEATURE_PUBLIC_SITE_AUTOPROVISION,
    ),
    FEATURE_ROLE_ONBOARDING_V2: Boolean(
      flags?.FEATURE_ROLE_ONBOARDING_V2 ?? PHASE1_FEATURE_FLAG_DEFAULTS.FEATURE_ROLE_ONBOARDING_V2,
    ),
  };
}
